Starting rank 0 on 3.94.129.141
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Starting rank 2 on 44.210.21.75
Starting rank 1 on 3.214.184.67
From https://github.com/cmbarrosb/machinelearningcc
 * branch            main       -> FETCH_HEAD
Already up to date.
From https://github.com/cmbarrosb/machinelearningcc
 * branch            main       -> FETCH_HEAD
Already up to date.
[W socket.cpp:601] [c10d] The client socket has failed to connect to [ec2-3-94-129-141.compute-1.amazonaws.com]:29500 (errno: 110 - Connection timed out).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [ec2-3-94-129-141.compute-1.amazonaws.com]:29500 (errno: 110 - Connection timed out).
[W socket.cpp:601] [c10d] The client socket has failed to connect to ec2-3-94-129-141.compute-1.amazonaws.com:29500 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (3.94.129.141, 29500).
Traceback (most recent call last):
  File "train_ddp.py", line 113, in <module>
    main()
  File "train_ddp.py", line 57, in main
    torch.distributed.init_process_group(backend='gloo', rank=rank, world_size=world_size)
  File "/home/ec2-user/machinelearningcc/venv/lib64/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ec2-user/machinelearningcc/venv/lib64/python3.7/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/ec2-user/machinelearningcc/venv/lib64/python3.7/site-packages/torch/distributed/rendezvous.py", line 178, in _create_c10d_store
    hostname, port, world_size, start_daemon, timeout, multi_tenant=True
RuntimeError: The client socket has failed to connect to any network address of (3.94.129.141, 29500). The client socket has failed to connect to ec2-3-94-129-141.compute-1.amazonaws.com:29500 (errno: 110 - Connection timed out).
[W socket.cpp:601] [c10d] The client socket has failed to connect to ec2-3-94-129-141.compute-1.amazonaws.com:29500 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (3.94.129.141, 29500).
Traceback (most recent call last):
  File "train_ddp.py", line 113, in <module>
    main()
  File "train_ddp.py", line 57, in main
    torch.distributed.init_process_group(backend='gloo', rank=rank, world_size=world_size)
  File "/home/ec2-user/machinelearningcc/venv/lib64/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ec2-user/machinelearningcc/venv/lib64/python3.7/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/ec2-user/machinelearningcc/venv/lib64/python3.7/site-packages/torch/distributed/rendezvous.py", line 178, in _create_c10d_store
    hostname, port, world_size, start_daemon, timeout, multi_tenant=True
RuntimeError: The client socket has failed to connect to any network address of (3.94.129.141, 29500). The client socket has failed to connect to ec2-3-94-129-141.compute-1.amazonaws.com:29500 (errno: 110 - Connection timed out).
Distributed training launched. Logs in logs/train_ddp_rank0.log, train_ddp_rank1.log, train_ddp_rank2.log
